/** Official docs or homepages for homepage tech chips */
export const techLinks: Record<string, string> = {
  "React Native": "https://reactnative.dev/",
  Expo: "https://expo.dev/",
  EAS: "https://expo.dev/eas",
  TypeScript: "https://www.typescriptlang.org/",
  JavaScript: "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
  "CI/CD": "https://docs.github.com/en/actions",
  "Node.js": "https://nodejs.org/",
  Go: "https://go.dev/",
  PostgreSQL: "https://www.postgresql.org/",
  AWS: "https://aws.amazon.com/",
  Firebase: "https://firebase.google.com/",
  SST: "https://sst.dev/",
  Cloudflare: "https://www.cloudflare.com/",
  Hono: "https://hono.dev/",
  Drizzle: "https://orm.drizzle.team/",
  "ai-sdk": "https://ai-sdk.dev/",
  Tauri: "https://tauri.app/",
  Bun: "https://bun.sh/",
  Solana: "https://solana.com/",
  Privy: "https://www.privy.io/",
  Bridge: "https://www.bridge.xyz/",
  x402: "https://www.x402.org/",
  Vite: "https://vite.dev/",
  "Next.js": "https://nextjs.org/",
  Gemini: "https://ai.google.dev/gemini-api/docs",
  Docker: "https://www.docker.com/",
};